#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

## Display environment
echo "+-------------------- ENV VARS --------------------+"
env
echo "+-------------------- ENV VARS --------------------+"

## Vars ----------------------------------------------------------------------

export DEPLOY_AIO="true"

## Main ----------------------------------------------------------------------

echo "rpc-component-1 at SHA $(git rev-parse HEAD)"
echo "rpc-component-1 periodic tests running..."
sleep 1
echo "rpc-component-1 periodic tests completed."

