#!/bin/bash

set -xeu

## Display environment
echo "+-------------------- ENV VARS --------------------+"
env
echo "+-------------------- ENV VARS --------------------+"

echo "Deploying rpc-component-1 ..."

echo "Successfully deployed rpc-component-1" > /tmp/rpc-component-1
